### ISSUE TITLE
 Bitmex vs. Binance

### ISSUE THREAD

**Issue by waynelapierre** [hfshr/bitmexr#2]
I found your bitmexr package very useful. Do you have any plan of creating an R API to Binance data?

**Comment by hfshr** [comment]
Hi @waynelapierre, I'm glad you find the package useful! I don't have any plans for a Binance package, but you could check out https://github.com/daroczig/binancer which should have everything you need for accessing Binance data from R.

**Comment by waynelapierre** [comment]
thanks for the information. people say Bitmex nowadays has higher trading volumes than Binance while others say the opposite. I will try to figure this out using these two R packages.
